### ISSUE TITLE
Unchecked LTS core and LTS modules

### ISSUE THREAD

**Issue by soundspeachy** [d6lts/hacked#1]
Using the Hacked 6.x-2.0-beta9 release, the module does not appear to be checking core and modules that have been updated using the mydropwizard module via drush up. I get "Unchecked Drupal core 6.44", and the same unchecked for Hacked! 6.x-2.0-beta9, FileField Sources 6.x-1.11, FileField 6.x-3.15, and others.  The module checks modules installed from ddo, like "Unchanged myDropWizard 6.x-1.70 files changed, 0 files deleted"

Am I doing something incorrectly?

**Comment by dsnopek** [comment]
Hm. The only thing I can think is that Drupal.org update status data could be cached? If you're doing this with drush, try doing `drush cc drush` or if in Drupal, then clear the normal Drupal caches.

All I can say besides that is that it works for us!
